# Site
name: "BoostKPI"
title: "BoostKPI Docs"
description: ""
email: contact@boostkpi.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.boostkpi.com"
favicon_ico: "/assets/ico/favicon.svg"
logo: "/assets/logo/boostKPI_logo.svg"

# Authors
authors:
  sal:
    name: Amit Manjhi
    display_name: Amit
    avatar: 'assets/images/avatar-sal.png'
    email: amit@boostkpi.com
    web: https://www.boostkpi.com
    twitter: https://twitter.com/boostkpi
    description: ""
# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Other
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
